from round23_practice_data import apply_round23_practice_data


def p(problem_id, title, category, return_type, method, *params, kind="solution"):
    return {
        "id": problem_id,
        "title": title,
        "category": category,
        "kind": kind,
        "return_type": return_type,
        "method": method,
        "params": list(params),
    }


def design(problem_id, title, kind, category="design"):
    return {
        "id": problem_id,
        "title": title,
        "category": category,
        "kind": kind,
    }


def special(problem_id, title, category, kind):
    return {
        "id": problem_id,
        "title": title,
        "category": category,
        "kind": kind,
    }


ROUND2_PROBLEMS = [
    p(14, "Longest Common Prefix", "string_array", "string", "longestCommonPrefix", "vector<string>& strs"),
    p(28, "Find the Index of the First Occurrence in a String", "string_array", "int", "strStr", "string haystack", "string needle"),
    p(58, "Length of Last Word", "string_array", "int", "lengthOfLastWord", "string s"),
    p(151, "Reverse Words in a String", "string_array", "string", "reverseWords", "string s"),
    p(189, "Rotate Array", "array_greedy", "void", "rotate", "vector<int>& nums", "int k"),
    p(169, "Majority Element", "array_greedy", "int", "majorityElement", "vector<int>& nums"),
    design(380, "Insert Delete GetRandom O(1)", "design_randomizedset"),
    p(12, "Integer to Roman", "math", "string", "intToRoman", "int num"),
    p(13, "Roman to Integer", "math", "int", "romanToInt", "string s"),
    p(36, "Valid Sudoku", "matrix", "bool", "isValidSudoku", "vector<vector<char>>& board"),
    p(42, "Trapping Rain Water", "stack_queue", "int", "trap", "vector<int>& height"),
    p(392, "Is Subsequence", "two_pointers", "bool", "isSubsequence", "string s", "string t"),
    p(16, "3Sum Closest", "two_pointers", "int", "threeSumClosest", "vector<int>& nums", "int target"),
    p(18, "4Sum", "two_pointers", "vector<vector<int>>", "fourSum", "vector<int>& nums", "int target"),
    p(76, "Minimum Window Substring", "sliding_window", "string", "minWindow", "string s", "string t"),
    p(239, "Sliding Window Maximum", "monotonic_queue", "vector<int>", "maxSlidingWindow", "vector<int>& nums", "int k"),
    p(904, "Fruit Into Baskets", "sliding_window", "int", "totalFruit", "vector<int>& fruits"),
    p(1493, "Longest Subarray of 1's After Deleting One Element", "sliding_window", "int", "longestSubarray", "vector<int>& nums"),
    p(1004, "Max Consecutive Ones III", "sliding_window", "int", "longestOnes", "vector<int>& nums", "int k"),
    p(1658, "Minimum Operations to Reduce X to Zero", "sliding_window", "int", "minOperations", "vector<int>& nums", "int x"),
    p(74, "Search a 2D Matrix", "binary_search", "bool", "searchMatrix", "vector<vector<int>>& matrix", "int target"),
    p(875, "Koko Eating Bananas", "binary_search", "int", "minEatingSpeed", "vector<int>& piles", "int h"),
    p(162, "Find Peak Element", "binary_search", "int", "findPeakElement", "vector<int>& nums"),
    p(34, "Find First and Last Position of Element in Sorted Array", "binary_search", "vector<int>", "searchRange", "vector<int>& nums", "int target"),
    p(81, "Search in Rotated Sorted Array II", "binary_search", "bool", "search", "vector<int>& nums", "int target"),
    p(540, "Single Element in a Sorted Array", "binary_search", "int", "singleNonDuplicate", "vector<int>& nums"),
    p(658, "Find K Closest Elements", "binary_search", "vector<int>", "findClosestElements", "vector<int>& arr", "int k", "int x"),
    p(1539, "Kth Missing Positive Number", "binary_search", "int", "findKthPositive", "vector<int>& arr", "int k"),
    p(92, "Reverse Linked List II", "linked_list", "ListNode*", "reverseBetween", "ListNode* head", "int left", "int right", kind="listnode"),
    p(24, "Swap Nodes in Pairs", "linked_list", "ListNode*", "swapPairs", "ListNode* head", kind="listnode"),
    p(61, "Rotate List", "linked_list", "ListNode*", "rotateRight", "ListNode* head", "int k", kind="listnode"),
    p(143, "Reorder List", "linked_list", "void", "reorderList", "ListNode* head", kind="listnode"),
    p(2, "Add Two Numbers", "linked_list", "ListNode*", "addTwoNumbers", "ListNode* l1", "ListNode* l2", kind="listnode"),
    p(25, "Reverse Nodes in k-Group", "linked_list", "ListNode*", "reverseKGroup", "ListNode* head", "int k", kind="listnode"),
    p(138, "Copy List with Random Pointer", "linked_list", "Node*", "copyRandomList", "Node* head", kind="random_list_node"),
    design(146, "LRU Cache", "design_lrucache"),
    p(82, "Remove Duplicates from Sorted List II", "linked_list", "ListNode*", "deleteDuplicates", "ListNode* head", kind="listnode"),
    p(86, "Partition List", "linked_list", "ListNode*", "partition", "ListNode* head", "int x", kind="listnode"),
    p(22, "Generate Parentheses", "backtracking", "vector<string>", "generateParenthesis", "int n"),
    p(71, "Simplify Path", "stack_queue", "string", "simplifyPath", "string path"),
    p(394, "Decode String", "stack_queue", "string", "decodeString", "string s"),
    p(496, "Next Greater Element I", "stack_queue", "vector<int>", "nextGreaterElement", "vector<int>& nums1", "vector<int>& nums2"),
    p(503, "Next Greater Element II", "stack_queue", "vector<int>", "nextGreaterElements", "vector<int>& nums"),
    p(735, "Asteroid Collision", "stack_queue", "vector<int>", "asteroidCollision", "vector<int>& asteroids"),
    p(402, "Remove K Digits", "stack_queue", "string", "removeKdigits", "string num", "int k"),
    p(84, "Largest Rectangle in Histogram", "stack_queue", "int", "largestRectangleArea", "vector<int>& heights"),
    p(98, "Validate Binary Search Tree", "binary_tree", "bool", "isValidBST", "TreeNode* root", kind="treenode"),
    p(230, "Kth Smallest Element in a BST", "binary_tree", "int", "kthSmallest", "TreeNode* root", "int k", kind="treenode"),
    p(235, "Lowest Common Ancestor of a Binary Search Tree", "binary_tree", "TreeNode*", "lowestCommonAncestor", "TreeNode* root", "TreeNode* p", "TreeNode* q", kind="treenode"),
    p(236, "Lowest Common Ancestor of a Binary Tree", "binary_tree", "TreeNode*", "lowestCommonAncestor", "TreeNode* root", "TreeNode* p", "TreeNode* q", kind="treenode"),
    p(199, "Binary Tree Right Side View", "binary_tree", "vector<int>", "rightSideView", "TreeNode* root", kind="treenode"),
    p(114, "Flatten Binary Tree to Linked List", "binary_tree", "void", "flatten", "TreeNode* root", kind="treenode"),
    p(105, "Construct Binary Tree from Preorder and Inorder Traversal", "binary_tree", "TreeNode*", "buildTree", "vector<int>& preorder", "vector<int>& inorder", kind="treenode"),
    p(106, "Construct Binary Tree from Inorder and Postorder Traversal", "binary_tree", "TreeNode*", "buildTree", "vector<int>& inorder", "vector<int>& postorder", kind="treenode"),
    p(437, "Path Sum III", "binary_tree", "int", "pathSum", "TreeNode* root", "int targetSum", kind="treenode"),
    p(124, "Binary Tree Maximum Path Sum", "binary_tree", "int", "maxPathSum", "TreeNode* root", kind="treenode"),
    design(173, "Binary Search Tree Iterator", "design_bstiterator", category="binary_tree"),
    p(222, "Count Complete Tree Nodes", "binary_tree", "int", "countNodes", "TreeNode* root", kind="treenode"),
    p(215, "Kth Largest Element in an Array", "heap_priority", "int", "findKthLargest", "vector<int>& nums", "int k"),
    design(703, "Kth Largest Element in a Stream", "design_kthlargest"),
    p(973, "K Closest Points to Origin", "heap_priority", "vector<vector<int>>", "kClosest", "vector<vector<int>>& points", "int k"),
    p(692, "Top K Frequent Words", "heap_priority", "vector<string>", "topKFrequent", "vector<string>& words", "int k"),
    p(378, "Kth Smallest Element in a Sorted Matrix", "heap_priority", "int", "kthSmallest", "vector<vector<int>>& matrix", "int k"),
    design(295, "Find Median from Data Stream", "design_medianfinder"),
    p(621, "Task Scheduler", "heap_priority", "int", "leastInterval", "vector<char>& tasks", "int n"),
    p(373, "Find K Pairs with Smallest Sums", "heap_priority", "vector<vector<int>>", "kSmallestPairs", "vector<int>& nums1", "vector<int>& nums2", "int k"),
    p(39, "Combination Sum", "backtracking", "vector<vector<int>>", "combinationSum", "vector<int>& candidates", "int target"),
    p(40, "Combination Sum II", "backtracking", "vector<vector<int>>", "combinationSum2", "vector<int>& candidates", "int target"),
    p(46, "Permutations", "backtracking", "vector<vector<int>>", "permute", "vector<int>& nums"),
    p(78, "Subsets", "backtracking", "vector<vector<int>>", "subsets", "vector<int>& nums"),
    p(90, "Subsets II", "backtracking", "vector<vector<int>>", "subsetsWithDup", "vector<int>& nums"),
    p(79, "Word Search", "backtracking", "bool", "exist", "vector<vector<char>>& board", "string word"),
    design(208, "Implement Trie (Prefix Tree)", "design_trie", category="trie"),
    design(211, "Design Add and Search Words Data Structure", "design_worddictionary", category="trie"),
    p(417, "Pacific Atlantic Water Flow", "graph_grid", "vector<vector<int>>", "pacificAtlantic", "vector<vector<int>>& heights"),
    p(210, "Course Schedule II", "graph", "vector<int>", "findOrder", "int numCourses", "vector<vector<int>>& prerequisites"),
    p(684, "Redundant Connection", "union_find", "vector<int>", "findRedundantConnection", "vector<vector<int>>& edges"),
    p(547, "Number of Provinces", "union_find", "int", "findCircleNum", "vector<vector<int>>& isConnected"),
    p(841, "Keys and Rooms", "graph", "bool", "canVisitAllRooms", "vector<vector<int>>& rooms"),
    p(127, "Word Ladder", "graph", "int", "ladderLength", "string beginWord", "string endWord", "vector<string>& wordList"),
    p(752, "Open the Lock", "graph", "int", "openLock", "vector<string>& deadends", "string target"),
    p(399, "Evaluate Division", "graph_weighted", "vector<double>", "calcEquation", "vector<vector<string>>& equations", "vector<double>& values", "vector<vector<string>>& queries"),
    p(1091, "Shortest Path in Binary Matrix", "graph_grid", "int", "shortestPathBinaryMatrix", "vector<vector<int>>& grid"),
    p(743, "Network Delay Time", "graph_weighted", "int", "networkDelayTime", "vector<vector<int>>& times", "int n", "int k"),
    p(416, "Partition Equal Subset Sum", "dynamic_programming", "bool", "canPartition", "vector<int>& nums"),
    p(518, "Coin Change II", "dynamic_programming", "int", "change", "int amount", "vector<int>& coins"),
    p(91, "Decode Ways", "dynamic_programming", "int", "numDecodings", "string s"),
    p(139, "Word Break", "dynamic_programming", "bool", "wordBreak", "string s", "vector<string>& wordDict"),
    p(5, "Longest Palindromic Substring", "dynamic_programming", "string", "longestPalindrome", "string s"),
    p(647, "Palindromic Substrings", "dynamic_programming", "int", "countSubstrings", "string s"),
    p(1143, "Longest Common Subsequence", "dynamic_programming", "int", "longestCommonSubsequence", "string text1", "string text2"),
    p(72, "Edit Distance", "dynamic_programming", "int", "minDistance", "string word1", "string word2"),
    p(213, "House Robber II", "dynamic_programming", "int", "rob", "vector<int>& nums"),
    p(309, "Best Time to Buy and Sell Stock with Cooldown", "dynamic_programming", "int", "maxProfit", "vector<int>& prices"),
    p(714, "Best Time to Buy and Sell Stock with Transaction Fee", "dynamic_programming", "int", "maxProfit", "vector<int>& prices", "int fee"),
    p(763, "Partition Labels", "greedy", "vector<int>", "partitionLabels", "string s"),
    p(134, "Gas Station", "greedy", "int", "canCompleteCircuit", "vector<int>& gas", "vector<int>& cost"),
    p(406, "Queue Reconstruction by Height", "greedy", "vector<vector<int>>", "reconstructQueue", "vector<vector<int>>& people"),
    p(646, "Maximum Length of Pair Chain", "greedy", "int", "findLongestChain", "vector<vector<int>>& pairs"),
    p(45, "Jump Game II", "greedy", "int", "jump", "vector<int>& nums"),
]


ROUND3_PROBLEMS = [
    p(41, "First Missing Positive", "array_greedy", "int", "firstMissingPositive", "vector<int>& nums"),
    p(31, "Next Permutation", "two_pointers", "void", "nextPermutation", "vector<int>& nums"),
    p(50, "Pow(x, n)", "math", "double", "myPow", "double x", "int n"),
    p(135, "Candy", "greedy", "int", "candy", "vector<int>& ratings"),
    p(137, "Single Number II", "bit_manipulation", "int", "singleNumber", "vector<int>& nums"),
    p(260, "Single Number III", "bit_manipulation", "vector<int>", "singleNumber", "vector<int>& nums"),
    p(201, "Bitwise AND of Numbers Range", "bit_manipulation", "int", "rangeBitwiseAnd", "int left", "int right"),
    p(190, "Reverse Bits", "bit_manipulation", "uint32_t", "reverseBits", "uint32_t n"),
    p(191, "Number of 1 Bits", "bit_manipulation", "int", "hammingWeight", "uint32_t n"),
    p(338, "Counting Bits", "bit_manipulation", "vector<int>", "countBits", "int n"),
    p(85, "Maximal Rectangle", "monotonic_queue", "int", "maximalRectangle", "vector<vector<char>>& matrix"),
    p(316, "Remove Duplicate Letters", "stack_queue", "string", "removeDuplicateLetters", "string s"),
    p(456, "132 Pattern", "stack_queue", "bool", "find132pattern", "vector<int>& nums"),
    p(862, "Shortest Subarray with Sum at Least K", "monotonic_queue", "int", "shortestSubarray", "vector<int>& nums", "int k"),
    p(907, "Sum of Subarray Minimums", "monotonic_queue", "int", "sumSubarrayMins", "vector<int>& arr"),
    p(1438, "Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit", "monotonic_queue", "int", "longestSubarray", "vector<int>& nums", "int limit"),
    design(901, "Online Stock Span", "design_stockspanner"),
    p(918, "Maximum Sum Circular Subarray", "monotonic_queue", "int", "maxSubarraySumCircular", "vector<int>& nums"),
    p(1425, "Constrained Subsequence Sum", "monotonic_queue", "int", "constrainedSubsetSum", "vector<int>& nums", "int k"),
    p(1673, "Find the Most Competitive Subsequence", "monotonic_queue", "vector<int>", "mostCompetitive", "vector<int>& nums", "int k"),
    special(297, "Serialize and Deserialize Binary Tree", "binary_tree", "codec_tree"),
    p(212, "Word Search II", "trie", "vector<string>", "findWords", "vector<vector<char>>& board", "vector<string>& words"),
    p(572, "Subtree of Another Tree", "binary_tree", "bool", "isSubtree", "TreeNode* root", "TreeNode* subRoot", kind="treenode"),
    p(103, "Binary Tree Zigzag Level Order Traversal", "binary_tree", "vector<vector<int>>", "zigzagLevelOrder", "TreeNode* root", kind="treenode"),
    p(116, "Populating Next Right Pointers in Each Node", "binary_tree", "Node*", "connect", "Node* root", kind="nextnode_tree"),
    p(117, "Populating Next Right Pointers in Each Node II", "binary_tree", "Node*", "connect", "Node* root", kind="nextnode_tree"),
    p(1026, "Maximum Difference Between Node and Ancestor", "binary_tree", "int", "maxAncestorDiff", "TreeNode* root", kind="treenode"),
    p(987, "Vertical Order Traversal of a Binary Tree", "binary_tree", "vector<vector<int>>", "verticalTraversal", "TreeNode* root", kind="treenode"),
    p(1372, "Longest ZigZag Path in a Binary Tree", "binary_tree", "int", "longestZigZag", "TreeNode* root", kind="treenode"),
    p(648, "Replace Words", "trie", "string", "replaceWords", "vector<string>& dictionary", "string sentence"),
    design(677, "Map Sum Pairs", "design_mapsum", category="trie"),
    p(820, "Short Encoding of Words", "trie", "int", "minimumLengthEncoding", "vector<string>& words"),
    p(787, "Cheapest Flights Within K Stops", "graph_weighted", "int", "findCheapestPrice", "int n", "vector<vector<int>>& flights", "int src", "int dst", "int k"),
    p(778, "Swim in Rising Water", "graph_weighted", "int", "swimInWater", "vector<vector<int>>& grid"),
    p(1631, "Path With Minimum Effort", "graph_weighted", "int", "minimumEffortPath", "vector<vector<int>>& heights"),
    p(1514, "Path with Maximum Probability", "graph_weighted", "double", "maxProbability", "int n", "vector<vector<int>>& edges", "vector<double>& succProb", "int start_node", "int end_node"),
    p(1466, "Reorder Routes to Make All Paths Lead to the City Zero", "graph", "int", "minReorder", "int n", "vector<vector<int>>& connections"),
    p(886, "Possible Bipartition", "graph", "bool", "possibleBipartition", "int n", "vector<vector<int>>& dislikes"),
    p(1202, "Smallest String With Swaps", "union_find", "string", "smallestStringWithSwaps", "string s", "vector<vector<int>>& pairs"),
    p(1319, "Number of Operations to Make Network Connected", "union_find", "int", "makeConnected", "int n", "vector<vector<int>>& connections"),
    p(934, "Shortest Bridge", "graph_grid", "int", "shortestBridge", "vector<vector<int>>& grid"),
    p(1162, "As Far from Land as Possible", "graph_grid", "int", "maxDistance", "vector<vector<int>>& grid"),
    p(1293, "Shortest Path in a Grid with Obstacles Elimination", "graph_grid", "int", "shortestPath", "vector<vector<int>>& grid", "int k"),
    p(1971, "Find if Path Exists in Graph", "union_find", "bool", "validPath", "int n", "vector<vector<int>>& edges", "int source", "int destination"),
    p(990, "Satisfiability of Equality Equations", "union_find", "bool", "equationsPossible", "vector<string>& equations"),
    p(2092, "Find All People With Secret", "graph", "vector<int>", "findAllPeople", "int n", "vector<vector<int>>& meetings", "int firstPerson"),
    p(2421, "Number of Good Paths", "union_find", "int", "numberOfGoodPaths", "vector<int>& vals", "vector<vector<int>>& edges"),
    p(2492, "Minimum Score of a Path Between Two Cities", "union_find", "int", "minScore", "int n", "vector<vector<int>>& roads"),
    p(1129, "Shortest Path with Alternating Colors", "graph", "vector<int>", "shortestAlternatingPaths", "int n", "vector<vector<int>>& redEdges", "vector<vector<int>>& blueEdges"),
    p(802, "Find Eventual Safe States", "graph", "vector<int>", "eventualSafeNodes", "vector<vector<int>>& graph"),
    p(10, "Regular Expression Matching", "dynamic_programming", "bool", "isMatch", "string s", "string p"),
    p(44, "Wildcard Matching", "dynamic_programming", "bool", "isMatch", "string s", "string p"),
    p(115, "Distinct Subsequences", "dynamic_programming", "int", "numDistinct", "string s", "string t"),
    p(97, "Interleaving String", "dynamic_programming", "bool", "isInterleave", "string s1", "string s2", "string s3"),
    p(120, "Triangle", "dynamic_programming", "int", "minimumTotal", "vector<vector<int>>& triangle"),
    p(221, "Maximal Square", "dynamic_programming", "int", "maximalSquare", "vector<vector<char>>& matrix"),
    p(494, "Target Sum", "dynamic_programming", "int", "findTargetSumWays", "vector<int>& nums", "int target"),
    p(377, "Combination Sum IV", "dynamic_programming", "int", "combinationSum4", "vector<int>& nums", "int target"),
    p(279, "Perfect Squares", "dynamic_programming", "int", "numSquares", "int n"),
    p(740, "Delete and Earn", "dynamic_programming", "int", "deleteAndEarn", "vector<int>& nums"),
    p(931, "Minimum Falling Path Sum", "dynamic_programming", "int", "minFallingPathSum", "vector<vector<int>>& matrix"),
    p(1155, "Number of Dice Rolls With Target Sum", "dynamic_programming", "int", "numRollsToTarget", "int n", "int k", "int target"),
    p(474, "Ones and Zeroes", "dynamic_programming", "int", "findMaxForm", "vector<string>& strs", "int m", "int n"),
    p(673, "Number of Longest Increasing Subsequence", "dynamic_programming", "int", "findNumberOfLIS", "vector<int>& nums"),
    p(1048, "Longest String Chain", "dynamic_programming", "int", "longestStrChain", "vector<string>& words"),
    p(368, "Largest Divisible Subset", "dynamic_programming", "vector<int>", "largestDivisibleSubset", "vector<int>& nums"),
    p(790, "Domino and Tromino Tiling", "dynamic_programming", "int", "numTilings", "int n"),
    p(1035, "Uncrossed Lines", "dynamic_programming", "int", "maxUncrossedLines", "vector<int>& nums1", "vector<int>& nums2"),
    p(639, "Decode Ways II", "dynamic_programming", "int", "numDecodings", "string s"),
    p(312, "Burst Balloons", "dynamic_programming", "int", "maxCoins", "vector<int>& nums"),
    p(17, "Letter Combinations of a Phone Number", "backtracking", "vector<string>", "letterCombinations", "string digits"),
    p(51, "N-Queens", "backtracking", "vector<vector<string>>", "solveNQueens", "int n"),
    p(52, "N-Queens II", "backtracking", "int", "totalNQueens", "int n"),
    p(131, "Palindrome Partitioning", "backtracking", "vector<vector<string>>", "partition", "string s"),
    p(140, "Word Break II", "backtracking", "vector<string>", "wordBreak", "string s", "vector<string>& wordDict"),
    p(126, "Word Ladder II", "graph", "vector<vector<string>>", "findLadders", "string beginWord", "string endWord", "vector<string>& wordList"),
    p(332, "Reconstruct Itinerary", "graph", "vector<string>", "findItinerary", "vector<vector<string>>& tickets"),
    p(68, "Text Justification", "string_array", "vector<string>", "fullJustify", "vector<string>& words", "int maxWidth"),
    p(502, "IPO", "heap_priority", "int", "findMaximizedCapital", "int k", "int w", "vector<int>& profits", "vector<int>& capital"),
    p(857, "Minimum Cost to Hire K Workers", "heap_priority", "double", "mincostToHireWorkers", "vector<int>& quality", "vector<int>& wage", "int k"),
    p(659, "Split Array into Consecutive Subsequences", "heap_priority", "bool", "isPossible", "vector<int>& nums"),
    p(871, "Minimum Number of Refueling Stops", "heap_priority", "int", "minRefuelStops", "int target", "int startFuel", "vector<vector<int>>& stations"),
    p(123, "Best Time to Buy and Sell Stock III", "dynamic_programming", "int", "maxProfit", "vector<int>& prices"),
    p(188, "Best Time to Buy and Sell Stock IV", "dynamic_programming", "int", "maxProfit", "int k", "vector<int>& prices"),
    design(460, "LFU Cache", "design_lfu_cache"),
    design(432, "All O`one Data Structure", "design_allone"),
    p(224, "Basic Calculator", "stack_queue", "int", "calculate", "string s"),
    p(227, "Basic Calculator II", "stack_queue", "int", "calculate", "string s"),
    p(30, "Substring with Concatenation of All Words", "sliding_window", "vector<int>", "findSubstring", "string s", "vector<string>& words"),
    p(4, "Median of Two Sorted Arrays", "binary_search", "double", "findMedianSortedArrays", "vector<int>& nums1", "vector<int>& nums2"),
    p(23, "Merge k Sorted Lists", "heap_priority", "ListNode*", "mergeKLists", "vector<ListNode*>& lists", kind="listnode"),
    p(480, "Sliding Window Median", "heap_priority", "vector<double>", "medianSlidingWindow", "vector<int>& nums", "int k"),
    p(786, "K-th Smallest Prime Fraction", "heap_priority", "vector<int>", "kthSmallestPrimeFraction", "vector<int>& arr", "int k"),
    p(1011, "Capacity To Ship Packages Within D Days", "binary_search", "int", "shipWithinDays", "vector<int>& weights", "int days"),
    p(410, "Split Array Largest Sum", "binary_search", "int", "splitArray", "vector<int>& nums", "int k"),
    p(1235, "Maximum Profit in Job Scheduling", "dynamic_programming", "int", "jobScheduling", "vector<int>& startTime", "vector<int>& endTime", "vector<int>& profit"),
    p(1482, "Minimum Number of Days to Make m Bouquets", "binary_search", "int", "minDays", "vector<int>& bloomDay", "int m", "int k"),
    p(287, "Find the Duplicate Number", "two_pointers", "int", "findDuplicate", "vector<int>& nums"),
    p(632, "Smallest Range Covering Elements from K Lists", "heap_priority", "vector<int>", "smallestRange", "vector<vector<int>>& nums"),
    p(1531, "String Compression II", "dynamic_programming", "int", "getLengthOfOptimalCompression", "string s", "int k"),
]


ROUND2_PROBLEMS = [apply_round23_practice_data(problem) for problem in ROUND2_PROBLEMS]
ROUND3_PROBLEMS = [apply_round23_practice_data(problem) for problem in ROUND3_PROBLEMS]
